<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-20 22:55
=======
# Generated by Django 5.2.1 on 2025-05-20 22:15
>>>>>>> 7d1f4724631ce1731fd34bc61299ae2dc57e1018

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beblio', '0005_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='details',
        ),
    ]
