# Generated by Django 5.2.1 on 2025-05-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beblio', '0005_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='details',
            new_name='genre',
        ),
    ]
