# Generated by Django 5.2.1 on 2025-05-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beblio', '0005_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='details',
        ),
    ]
