# Generated by Django 5.2.1 on 2025-05-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beblio', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beblio.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beblio.user')),
            ],
        ),
    ]
