# Generated by Django 5.2.1 on 2025-05-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beblio', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
